/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.12 cbr450.gltf --transform
Author: Jacobdesigns (https://sketchfab.com/Jacobdesigns)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/free-honda-crf-450-c80f0e732e844580af412958c9d67315
Title: (FREE) Honda CRF 450
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/cbr450-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes._rootJoint} />
      <mesh geometry={nodes.BezierCurve005_HOSE_0.geometry} material={materials.HOSE} position={[-0.04, 1.14, 0.31]} rotation={[1.03, 1.41, -1.68]} scale={0.18} />
      <mesh geometry={nodes.Spiral_Honda_Red_0.geometry} material={materials.Honda_Red} position={[0, 0.39, -0.27]} rotation={[-1.33, 0, -Math.PI]} scale={0.66} />
      <skinnedMesh geometry={nodes.Object_40.geometry} material={materials.FENDERS} skeleton={nodes.Object_40.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={1.14} />
      <skinnedMesh geometry={nodes.Object_42.geometry} material={materials.NUMBERPLATES} skeleton={nodes.Object_42.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={1.14} />
    </group>
  )
}

useGLTF.preload('/cbr450-transformed.glb')
