/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.12 ducatiMonster.gltf --transform
Author: Charly Hayoz (https://sketchfab.com/charlyhayoz)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ducati-monster-8c5f5943533e47b8af90873f6c6c8563
Title: Ducati Monster
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/ducatiMonster-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.meshNode_Material_u1_v1_0.geometry} material={materials.Material_u1_v1} position={[344.9, -28.38, 5.74]} rotation={[-1.41, 0.02, 0.13]} scale={100} />
    </group>
  )
}

useGLTF.preload('/ducatiMonster-transformed.glb')
